const params = new URLSearchParams(window.location.search);
const userId = params.get("id");

if (localStorage.getItem("accessToken") == null && userId == "me") {
    window.location.href = "/login";
}

$(document).on("click", "i.del", function () {
    $(this).parent().remove();
});

$(function () {
    $(document).on("change", ".uploadFile", function () {
        var uploadFile = $(this);
        var files = !!this.files ? this.files : [];
        if (!files.length || !window.FileReader) {
            console.log("No file selected.");
            return; // no file selected, or no FileReader support
        }

        if (/^image/.test(files[0].type)) {
            // only image file
            var reader = new FileReader(); // instance of the FileReader
            reader.readAsDataURL(files[0]); // read the local file

            reader.onloadend = function () {
                // set image data as background of div
                //alert(uploadFile.closest(".upimage").find('.imagePreview').length);
                uploadFile
                    .closest(".imgUp")
                    .find(".imagePreview")
                    .css("background-image", "url(" + this.result + ")");
            };
        }
    });
});

function transferDataToHtml(data) {
    var fullNameField = document.getElementById("user-full-name");
    fullNameField.value = data.UserRealName;

    var emailField = document.getElementById("email");
    emailField.value = data.UserEmail;

    var phoneField = document.getElementById("phone");
    phoneField.value = data.UserPhoneNumber;

    var educationField = document.getElementById("education");
    educationField.value = data.UserProfileEducation;

    var avatar = "";

    if (data.UserAvatar == null) {
        avatar =
            "/9j/4QCERXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAITAAMAAAABAAEAAIKYAAIAAAAiAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABTWFyaWlhIFNoYXBpbG92YSB8IERyZWFtc3RpbWUuY29tAP/tAEpQaG90b3Nob3AgMy4wADhCSU0EBAAAAAAALRwCdAAhTWFyaWlhIFNoYXBpbG92YSB8IERyZWFtc3RpbWUuY29tHAIAAAIABAD/4Qx1aHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49J++7vycgaWQ9J1c1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCc/Pgo8eDp4bXBtZXRhIHhtbG5zOng9J2Fkb2JlOm5zOm1ldGEvJyB4OnhtcHRrPSdJbWFnZTo6RXhpZlRvb2wgMTAuODAnPgo8cmRmOlJERiB4bWxuczpyZGY9J2h0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMnPgoKIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PScnCiAgeG1sbnM6cGx1cz0naHR0cDovL25zLnVzZXBsdXMub3JnL2xkZi94bXAvMS4wLyc+CiAgPHBsdXM6TGljZW5zb3I+CiAgIDxyZGY6U2VxPgogICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSdSZXNvdXJjZSc+CiAgICAgPHBsdXM6TGljZW5zb3JVUkw+aHR0cHM6Ly93d3cuZHJlYW1zdGltZS5jb208L3BsdXM6TGljZW5zb3JVUkw+CiAgICA8L3JkZjpsaT4KICAgPC9yZGY6U2VxPgogIDwvcGx1czpMaWNlbnNvcj4KIDwvcmRmOkRlc2NyaXB0aW9uPgoKIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PScnCiAgeG1sbnM6eG1wUmlnaHRzPSdodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyc+CiAgPHhtcFJpZ2h0czpXZWJTdGF0ZW1lbnQ+aHR0cHM6Ly93d3cuZHJlYW1zdGltZS5jb20vYWJvdXQtc3RvY2staW1hZ2UtbGljZW5zZXM8L3htcFJpZ2h0czpXZWJTdGF0ZW1lbnQ+CiA8L3JkZjpEZXNjcmlwdGlvbj4KPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKPD94cGFja2V0IGVuZD0ndyc/Pv/bAEMACAYGBwYFCAcHBwkJCAoMFA0MCwsMGRITDxQdGh8eHRocHCAkLicgIiwjHBwoNyksMDE0NDQfJzk9ODI8LjM0Mv/CAAsIAyADIAEBIgD/xAAaAAEAAgMBAAAAAAAAAAAAAAAABQYBAwQC/9oACAEBAAAAAb+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHjTr8eXr3s3ewAAAAAAAAAAAAANfHx8vNrAGzp6uzs2AAAAAAAAAAAABqjo7kwAADPXIyO0AAAAAAAAAAAHFE8GAAAAZ75btAAAAAAAAAAAcMLyAAAAA65ruAAAAAAAAAAHPBcIAAAAA7p3oAAAAAAAAABiHh/IAAAAAPUxMZAAAAAAAAANFe5AAAAAAB12HeAAAAAAAABw17WAAAAAADZYe4AAAAAAAAIqCwAAAAAAAzOyoAAAAAAABDQoAAAAAAAJqZAAAAAAAAhoUAAAAAAABNTIAAAAAAARUCAAAAAAAAJ6VAAAAAAAOGt4AAAAywAAABmydwAAAAAAGir6wAABtk+7p2NfNwxmoAAAbLRvAAAAAADFY5AAAD3NSuQGIqF8AAAHXZ8gAAAAACGhQAADqse4AGmucoAABNTIAAAAABz1byAAA6rN7AAeKzygAAPVp6AAAAAAFa4QAAGy1bQABqqusAAB3WUAAAAADhrQAABYJMAAEZXwAACy9wAAAAAKvyAAAOi1gAAKpzgAAOu0AAAAABxVkAAAnJcAABEQYAABZu0AAAAAVyPAAALX0AAAOeqAAAEhYwAAAADVUsAAAPVxAAAFO8gAAM23aAAAAAiYIAAA32wAAAVPQAAATssAAAAArHGAAAb7YAAAKnoAAAOyzgAAAAa6jgAAA93AAAAU/wAAAZt2wAAAAEfXAAAAt20AABqqIAAAWOQAAAABBxAAAAWCTAAARlfAAACXnAAAAAVniAAADtswAACs8QAAAdtmAAAABUNYAAALP2AAA46wAAADZbwAAAA8U8AAADptOQADGuucgAAAFw9gAAADmqoAAACTsAAB4go/HkAAAFq6QAAABxVkAAD15Ak5/IAYQUZnzgAAAFm7QAAABH1wAAM49+MsZYdk71YxnHpjDlhOP34esMMsAABY5AAAAARteAAGWPfjIeffn13SXX6evWrijo9nGQBgAAWGSAAAAEbXgABlj35Y9YGM49N21r0+M4yxn14yxnLyAAFhkgAAABH1wAAZBjOD1hj1gM+cjGfXjLGTGMgAFjkAAAABxVkAAMsM4ZY29e736DOGNenk14zjOM4ywAAFm7QAAABzVUAAAG6TkekAAc0dGaQAAAWrpAAAAHingAADbNSeQAAGIyF1AAAC4ewAAAAqGsAABKTnsAAAHiDiwAAGy3gAAAArPEAADM/JgAAACMgMAAA7bMAAAACDiAAAzY+8AAAAHBXMAABLzgAAAAI+uAABYJMAAAABGV8AALHIAAAAA11HAABKzwAAAAAgYoAAzbtgAAAAFY4wAG+1egAAAAB5qugAB2WcAAAABEwQACxSIAAAAAI6ugAJ2WAAAAAaqlgAHRawAAAAAFU5wAZtu0AAAAArkeACdlgAAAAAETBAAkLGAAAAAOKsgBm27QAAAAAGqpYACzdoAAAAAVfkAHTagAAAAABVeYAddoAAAAABw1oASdgAAAAAAFfjABZe4AAAAACtcIBNzAAAAAAAh4QA7rKAAAAAA56t5AT8oAAAAAAIuAAerT0AAAAAAENCgLBJgAAAAACMr4CamQAAAAABiscgFgkwAAAAABGV8Drs+QAAAAAA0VfWCwSYAAAAAAjK+DZaN4AAAAAAHDW8BnIAAAAAAxgM2TuAAAAAAAIqBAAAAAAAAE9KgAAAAAABDQoAAAAAAACamQAAAAAAAIaFAAAAAAABNTIAAAAAAABFQWAAAAAAAGZ2VAAAAAAAADhr2sAAAAAAGyw9wAAAAAAAAGivcgAAAAAA67DvAAAAAAAAAMQ8P5AAAAAB6mJjIAAAAAAAAAOeC4QAAAAB3TvQAAAAAAAAAAOGF5AAAAAdc13AAAAAAAAAAAOKJ4MAAAAz3y3aAAAAAAAAAAADVHR3JgAAGeuRkdoAAAAAAAAAAAAa+Pj5ebWANnT1dnZsAAAAAAAAAAAAAA8adfjy9e9m72AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//EACsQAAEDAwIFAwUBAQAAAAAAAAMBAgQAEUASUBATFDAxIDNCISI0QWAyoP/aAAgBAQABBQL/AJpVe1KWQJK6sNdYKutFXWirrBV1YaSQJaR7V/lnPa2nTBJTpzqWUZaV7l7aPc2klGSmznU2YJaa9r/455GMp85KfJK/FZJKymTkphGP/iSSRjoksj685PihyyMockZP4Uspg6JIITPHIIOhSmE/gSGYJCynk2MUp46GZhU3y9kNMpVVV2RFVFDMpFum8kK0TTHcVdoCdwlGVpW7ueSgqc5Xu2prlY4ElC7tIladvjytW6SZW4xpW5SZO5xZO4SpGndYsjVt0k/KblWq2XGPzW7WUiCY5yvdjMG8lMgrTYom0jGpxVjVp0UTqfBWnjePHY5WOERCs2lfohzc1+K1qvUUNEpERE7CoioWGi05qsXFAblPT6ptEw2MELjOGJom9wgmlaYLguxYZtoMTlDVbriBCpntajG95zUe0wVC/ERbKEnNHs0kvMJiMYr3jGgmYBBoVj2Kx+JFLyybLKLyxYsMWlmFMFqZixS8wWySCcwuIEfMLiGHyy4kcnLLscknLDiwWfbiTmfbixScwOxSyazYoG6Q4h26g4sQmg2wkfoH5XEal3YypZ2J4Ub9Y9gnP+3FD72MX3sWC/7dgkv1nxQ+9jG97FjP0Hz3u0MxmLZ+M9bvxmO1szpjrAxxO1CxCu0ix4brgzpzvux4T7ixJr7Cx4LvuzpS3kY8UnLNiSicw2PFW0jOeup+RGLzRYUkvKFkMXS/NetmZIS8oiKjkwHKjUK/nPyWLdmZIW0fKiyOWvf/AFIPevKLkx1vHzJf4+HbsR5PLpFRU7iqiIaRzOHhFyYn4+ZM/Hwl8fP0WX0CMQKiOwvG9Xq/ovweZo6KYheF3cbLwsuND/HzJvsYPmv180rzw8VppONk4DmEZTZQ3UiovFOCuRKfKE2nSnvXyn04fFfNWSvPo81/lV84EL2Myb7GD+q+SV+q+Sf5r98Vr5ItlQxErqi11RbKcq1e60nn48Pi7z8+CV8f1+/GFC9jMmfj4Pir144fqvNfRa+nH6LwXz8v3w/X0T0eK88Pi7z8+CV8eCW4frvw/wAfMl/j4V19V1q/Bo3upIplpIT66CuhroEroa6Guhroa6GugroK6F6U6KanDe3tXXCifj5khLx8hgnkpkGmgGzBcAb6fBp4njyY6Wj5j0uzGYNxFFDa2kS2La9FhtdTxuGuMxLMzXppfiBiK+mtRiZDmo9DRFZisS786UlpGEiXWPFRmbIio+lSy4UVLyM6c37sFEuseOgkzpEdCoqWXBgt+7OmNuDBix9CbBKj60wYbbAznt1MwIgNS7FLBpXAY3QzPks0H7whqUjURrdiVEc0o1ETvRmaz7BOZ9veiC0D2SWLWPvQWfbsBGax+F7gR8wuzGHyy9zyo2aB7DLHoN3ILLN2aay7e5EHrNsUkfMD3Bt0D2YjdY+5FHyw7HIHyy9oDdR9oO3SftRx8wuyShcwXahJc20TUsbtRRcsWyyhcsnZgJ9Nonp9OzFFzCbMYfNGqWXsQfa2id7XYRLqEfKHs8wPZg+ztE32exDDtKpdDh5T/XB9naJvs+sAea9Esm0lGhWOarHeqF7O0TfZ9TGq9whoJm1yQc1vrutXWrrV1q61dautXWrrV1q61dautXWrrV1q61dautXWrrV1q61dautXWrrV1q61dautXWrrV1q61dautXWrrV17EYHKbtsqPq3WLH07hJjbnFjblJi7jGi7pIi6tvjxdO7HjIWnNVjtqa1XuBGQW8EE0rTAcJdoCBxVGJom7za6Gh0qKi7IiKqhh0iWTfCBYVCxXj2MUV5KGFgk/gCxWEokcg88cchKFFYP+FJFGSiRCMrxk+aHEI+hxRj/AIl42Pp8FKfGKzFZGK+mQUpg2M/jnMa6nQxLToLqWKZKVjk7aMc6kimWmwXU2GJKaxrP5ZWNWljiWukDXRirohV0Qq6MVdIGkjiSkY1P+ab/xAAxEAABAgMFBwMEAwEBAAAAAAABAAIRMUAhIjJQURASMEFhcYEDkaETIDNgQmKxoOH/2gAIAQEABj8C/wCaW1wWMLF8Ln7L+S/kufssXwsYVjh+rXnAKyJV1oWKHZWuPDscVij3V5oVsQrrgf0684BXGx7rFDtS4o91fbDsrrgf0mcT0Vl0Vdt4KcD1/RYYj0U4DQV84jQqGE/oN4+FCTcjhiarpt0z21Q9P3UTksQoep7qzOouWjdMp1bootziAtcouMTlcWmBUDY7Ntxk9cv3Hz1zTc9Pycx3PU8HMvps8nM/pv8ABzDcZPnmu4+fLLoDEc3gcQyzeKLjOnutir7vZYY91Y0bbWhYYdlcd7q82FOHCa3hlUV/USpoNESo+padFAcGBUfTsOig4QNN/UzUcp+mPNNZLVQaOLBwVstab6Z8ZQXc+SiaWHLmVutlx910lDlyNLEIO588nswilDQt0UO6UWmltwnJrJmm3zM0e+JimtmMlOglShtKW0o0M8kOpspnP8UrX+KYaizI4cm0zR0pXDpTQ5OyIu0pgKcimDtchDNaZnenf3pnM0yF3SymZ3p396ZvWzIC7SnB607j1pw7WvhrUNPSlcelRDSva2oLdKXd1qHNr3VA0NlKdBZUNr3HrU9ROj6mVS09a5x6VUeXNREqGLiog9qpp6Vr+1XuOw/5QErdbJRkQo61LO1a6khz4G6/D/iiOLEosbhVokiTM1Ta3zSHg2WjRWWHQ8GWy0xOitsGlb5rfNF02HZ0+yHLZBT+FBW3goGw9VZA/baVr2CsuhRK/wDNpUFPZZtiaPzW+aE9l52FeNoX+qGx2xqKchBG+Ub3JC8sZTY7fP2HYE5eF5XleLF1ovNb5ouis2eNvVWhc9kdjUU7sgnI9kNkdvRQG0o7HbPOyBXOi81rqrlsutKkAsYX5Phfk+F+T4X5Phfk+Fj+F+T4X5Phfk+F+T4VjwpR7K1pFY2tf2qbrYq+72VjRQ2tCuO91ebCpZ2rXDpTwaFF94qyltUWXSoOFO0dK5w60u8+wKDRAVMHCIW8y0UrR1r3UcAt59rq3eZY5QNG2va6igFE4q+IxqBonOr46UW+7F/mQ77cX+0Uda8t1ofqOkJZH9RsjOhDdMgd1t44aoCWRkGSLeOOluQh+nH3jN2S7wm3jl+uQluvGDcnLeMG6ZFHk7il+uTh+nFjybkZ1FvFa3J3N4o1NuSHQy4bR1ylw68MaCeS2THDJ0GUg6jh2zOTWYTwnnKWHhW4Rk5bz5KB4Lu+Ut78GAQbz55R9QeeCe+UjvwfqHxlMF/Uy4B75SO/A/qJqGVbpRaZ/ee+Ujv94aJrdGWRGIcCampqampqampqampqampqampqampqampqampqampqampqampqampqfAicRy7fZPnmu++fLMPqM8jM/qP8DMt/0/IzHf8AU8DNN9k9Mv33z0zaIscoOEDlcGiJUTa7OIOWrdcp0bqoNzq1R9P2UDksAo+p7KzPbw8qOJuRxk1XRbr+gxwlSiNRXygNSo4j+iygeisvCrtuhSiev6TeaCrjod1hj2pcMO6vuj2V1oH6deaCrIhXXBYY9la08OxpWGHdXnBWxKutA/VrWhYAsPyufuv5L+S5+6w/KwBWNH/NN//EACwQAAECBQQBBAMAAwEBAAAAAAEAESExQEFhUFFxkYEQMKGxYMHwIKDR4fH/2gAIAQEAAT8h/wBaWRnkqZeNEFx4JZ1YuixdEN9QJcOSUi86mZ4P4sH7Ar6UhFSXJdfqYym95Pty68FfqYgprgsr6chBugP4cFdQDAmUCmjG0CJJLkuaMEguCxWyG0SJgTKJBX/CYgnCSCeJNEknJJOakEk4JBwoJ5k1BOF+CnIDhSGmvJDQiRIcJ/Ab6LBNPYHENDayOArzoFPXSBCTAXKm/wB8IiISTc6KBEIIuFL/AL5QAEnBuNaehwLlRdgDSYOyEnsci41gH4nZHzw0seaCB+J31YTyvfsRJJclydNBILgsUJpWt3aow5uHUXGNy6k05eD61Nxi8n1qDMmjm21VmDQzb6cDjbCJJJJLk1TtinbGqBILgsQgc7Z0wt8A3KPy5U5RjIRFnCbsZKTvgJhsmGym75C3YyQEXMIUY1OLywIP8g2OlECEWARn8AUw6ZgTeTAkmEADYeywgEbFP5MiSLTAb0xn8AIgAC4Ok3v+2pmRAE080Bufd8UBuEyIilTL3/baQPjAZRDEcmJpWogKB4DB758ByT0ROlCCIxEQh8YDOjv4KyKUCMShXynehNLsjsgIxFLBysnRnAFbFNBjbwKODW/kU0AK2dFfw2qVtVM8IBgwlRkOGMltVMcUr+O1oiEDZUzBF4KVwC0VNEButDhHY803k5S+Tgpox2POhAN2IkkJmaXIBZAMGpSHDLEBalBICJhCF2aCwNc5pgcGNOLAzpnDLnGg4lApoeLTxc2mxKJoGJjolySZmmwUBp8kEaYFi4mFiY9fmhtUZLClwWVRnhtXvbYPUbkH8UrFcfxUNb4PX8MhURAbqlgA2VRyyFfkUjUsDm1RnBjaqWJQNdgwjVGFegGEMmcpGgJsJotJYTKfjGEh2qsmAa1wVaIMcikx75LSkVDxd26MYAlGRsVLgrRNmajsmOYmCfsHZGsKARAQbj2yWQIKIiAAXKj+27dRDApMhCjsBAUzCQDVJPietncKIAmQdAQTo/B+kJIAmQTET9MCIImG9MKEG6ZUELdnehLLgsIrIepLJyEuyHyHdFGfBAoggxgUCSKnOeVgLB8oAmQKwdeoBMgiCJiFF9ytkcaEByAugos8B4o/B+kDsFuMAWwEgnY9ygBLEx4U6LKIh8r+UCBLxRsdkAbzJow5vBA7nwI98r+ki9IgAPuU4gF+37k3LiU00Qu0nTbymwEgjJyV85RDBMzQJAA/CjCTDKZolLDI2O6FyZBSOIiQY0RO51sjjQj7Fahkj8ZV3JW8+g8bBASwTdCYMlvuhJyF8v8A303f01NyR+AozoRGyHtgtfKHlVgopnYKa+MsnFETAT9PoKH9cIXewRaBEHRk5PobuP0h9gr+SmPJWJegkV/e1FO51oxcKEFiCuxoAJI8umY1z8ITPJW8+jMhIiSXMJ9vZEfIcKMvlCxA8wVv5dfIR+Qh8it4faH2I/cjILk8sgY7RL0BYgrbMlsEdhIQRk5Pofo/SFuQrrN4KsQNEGRUgynSwZ6bmoPuVoPiaiBIkWWTr0lEIkmfrkfkJ3/wruURicgIPFxuUPMPh0NyIgxNMhC6Zo0FwSNP/KwBnq0zIozch2IP2uEGJAyXyOBAkSPo5Znh6EkzKkXCd9vA9ASJGGy4BwFZfz0ANmetYFSIMbKyveJL/tzGhvy3EFe8SEGNlapYFayYQp3+z+lFnBZABgAGwpSAMAI2Kdi4LJ/sfunxYArsKkKVod27lBomCpLRCbp4d27ilz6Ar+WRoyAA5NkyD2BtWug9wbohAMRaj4ZGva3waiIIDkyCnjP4r5Iw+UQwGImKJ7bBq/PDeigbFIaCgbBMUTPDevxcZEMSDMUEINhudDhBsNjQAOWEysTG0BpWge+IPk7BBQ2AMNDGE5BiiBtI7j32naJoLg1zH34Tf8tFhN/y99g65hoIDdiIJAZj3drpnhCAYaLMMtrpjj3QCACZQhdmhQjuefddecA0dt5wH3Yx3POhwgLL3ceDR8+D3YgF1ojeG97baqLSdiovbbx3tFOBC+NfwMCIBfOjO5C6Pa6ANJ7APai4XTo4+cFlEMBiIH2QiaTCJ7MggOTAIfOCzpFr/t9bGbX/AG+kgIQcFGbyFrK6ZvISAAAwGlFvgOxQ+WDV90PLkg/yHc6YDjbKIIJBDEf5AkSJWR2sjtZHayO1kdrI7WR2sjtZHayO1kdrI7WR2sjtZHayO1kdrI7WR2sjtZHayO1kdrI7WR2sjtZHayO1kdrI7WR2sjtZHayO1kdrI7WR2sjtZHayO0STMn/IAksA5KBztjTmZFDJvqrMCjk21B5w8H3qbDB5PvUnHFw6iwwuXVBPC1+5EEFiGI00AksA5Qmhe3ZqwPzO6PmhpY88ED8ztrDUODcKLsAaTB2Qk1jk3OtECAHBsVN/vhEQCCLHRQIBJNgpf98oAADAWGu30WCaewGQaG1kMxXnQKf4C5AMoUdNeSOhEiQZT+CxLlJFPEmiCTEEHNSASYAk4UU8yaiHK/CQVlBMSYRKaMbxIggsQxowCSwDlbIbwIGJMIEFb8OgP2AV1OCgprkMv3MUnvI9ufXgL9zGRUlwHV9OSg3QD8WmZ5CmXjRJcOCWNWbss3ZDbUAXHklIvOpGeB/rTf/aAAgBAQAAABD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD4Yf8A/wD/AP8A/wD/AP8A/wD/AP8A+H/h/wD/AP8A/wD/AP8A/wD/AP8A/H//AOv/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD8/wD/AP8A/wDz/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wDn/wD/AP8A/wD+f/8A/wD/AP8A/wD+/wD/AP8A/wD/APf/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AM//AP8A/wD/AP8A/wA//wD/AP8A/wD9/wD/AP2b/wD/APv/AP8A/wD/AP8A/wD/AP8Av9//AP8A/wD/AP8A/wD/APf/AP8Az/8AP/8A/v8A/wD/AP8A/wB//wD9/wD7/wD/AO//AP8A/wD/AP8A/wD/AL//AN//AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AH//AO//AP8A/wD/AP8A/wD/AP8A/wDv/wD/AH//AP8A/wD/AP8A/wD/AP8A/v8A/wD3/wD/AP8A/wD/AP8A/wD/AP8A7/8A/wB//wD/AP8A/wD/AP8Af/8A/f8A/wD7/wD/AO//AP8A/wD3/wD/AP8A/wD/AP8A/wD+/wD/AP8A/wB//wD/AP8A/wD/AP8A/wDv/wD/AP8A7/8A/wDv/wD/AH//AP8Af/8A/wD+/wD/AP8A/wD/AP8A/wD/APf/AP8A/wDv/wD/AP8A/wD/AP8A/wD/AH//AP8A/v8A/wD/AP8A/wD/AP8A/wD3/wD/AP8A3/8A/wD7/wD7/wD/AP8Av/8A/wD9/wD/AP8An/8Ar/8A/wD7/wD/AP8A3/8A+f7/ANP/AP8A/wC//wD/AP3/AP8AA298Wd//APv/AP8A/wD/AP8A4T3te4D/AP8A/wD/AP8A/wD/AP4Dtocjr/8A/wD/AP8A/wDf/wDjfEASOH//AL//AP8A/f8A/wB3zukVU/8A+/8A/wD/AN//AP8A7/8A/wB//wD/AL//AP8A/f8A/wD/AP8A/wD/AP8A/wD7/wD/AP8A7/8A/wB//wD/AO//AP8Af/8A/wD+/wD/AO//AP8A/wB//wD3/wD/AP8A7/8A/f8A/wD/APv/AP8Af/8A/wD+/wD/AP8A/wD/AP8A/wD/APf/AP8A/wD3/wD/AP8A/wD/AP8A/wD+/wD/AP8A/wB//v8A/wD/AP8A9/8A7/8A/wD/APf/AP8A/wD/AP8A/wD/AP7/AP8A/wD/AP8A/v8A/wD/AP8A9/8A/wD/AP8A/wD/AP8A3/8A/wD/AP8Av/8A/wD/AP8A/wD/APn/AP8A/wD/APn/AP8A/wD/AP8A/wD/AL//AP8A/wD/AN//AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AL//AP8A/wD/AN//AP8A/wD/AP8A9/v/AP8A/wD/AP3+/wD/AP8A/wD/AH//AP8A/wD/AP8A/wDv/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AN/AAAAAAD+//wD/AP8A/wD8/AAAAAAD8/8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A7/8A/wD/AP8A/wB//wD/AP8A/wD/AP5//wD/AP8A/wDn/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wDP/wD/AP8A/wA//wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8Ax/8A/j//AP8A/wD/AP8A/wD/AP8A/wCH/h//AP8A/wD/AP8A/wD/AP8A/wD/AIYf/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/8QALBABAAECAwcEAwEBAQEAAAAAAREAITFBUUBQYXGBobGR0fDxEDDBYOEgoP/aAAgBAQABPxD/AOaSYxrs2pXlknx+PgTwXlT6L719F96XiPP8Pg8ukea7dq0M4f5WbB8AqZGvKPVqQDdWX8qduGgUb9VWsf04Ul6qlZ6GgNQAbqy/tQI+aj1KmgfAf8dyGBbvSptTrQ9MakhX+JxpEhMVZdjBKDMYaggZ5PljUWp1oemNchgG50/xGFT1r4/q4VLINl/anrhiqV2k6YYKhKhkCy/tUde+HPJwrH/CWcnOsc2kWXcA667eyQ7iHTSoeU59nk/4GaSMzCq4FZ93m7jsBGfc5NTSwMgN+lkFKkBUXRrPD+0oNpUldyuDaRISpOjCeH9oMgpEkd9W11wexS4cDdW66u6Yc5G6t00avjpi9zfDSFy2TifanjZhy4G63jZgz4NFITL5OI9t7QlYJ3OE40jciVWV3aDcDIjCVCFgvY4XjvTOTh4B77xzk4Ix4PvvLPTg7Dg3nmpwdjxbwwpaBy6c964QtC5dOe7pRCVmjVpGyJVxXahcG5FI4l02om5EiYjUogOzRqbsvvpbP0KnDGXhw2fjESFjm0cC4eX1aOJ4pnthR8cpSgMAdKUxHpR8cpWjmJWbHbCjkek4fUrhESlnk7PKGMnHhVs9wz9DdQ4hSrkU3KnQWvN2ZOIwBQg2NNZz1oQN4BAfpULeISNCDY013LSsbiANmLtXoLXmUOIUiZm6YeuR22ZBGdfLHu1ZWXFxOL+1VOcnE4NQRnWyz7OzS9cnvugsIeoUe4tRzdlvgudA0ONHZLAHn952Swj5pxJc6ho8dle4sQyaGEHQNzrykvHc3ZZszxyNaEaxfMWa7CJ1uYWSVFmeOZrssDEh4Lk7mtadPM35rsw4ecXxvsY4acHxts0XMj45k7kwqTU+hGfXZUjb2XgxoCAAQBlsYIAohHOkj7WXiw2WbUehOfSsdx4au84vps0YruTgY/OGyxiu5ODh847Niq7Tg+m45BJCPl7dNmt/DBc2/wDdlt/LLmF/5s0QkBPw9uu4s5xTi5d6cOUVdXZeBX6mgAYBBsoKsEhrjV+h2Vw4QR0ayHFeDn33DLa/QjDv42aTs/Js8XZeTZp5X6E49/O4ZAMt6GPedmUt+Ds7FnwdmkCw3qYd43AK2C9lI4lJXZvoaGi5Oy4E18Eh2ZDSEkaEbAezb5Ytj0F3xtAGszHnF9lB1iYc4ttEE256MTzt8CtnfNY/m0TK5Pmv5nZYnc2cF/MbRIrYzzGP7t+P7RPQ2gLK7zg+uyhdXacX12jH9pvqbdgTU6f9jaMKFM1u10euximK3aavTaYU/wCxRcnbfksDWO0n2XnD3UAoMhmbAk2XFfAodg5kgPSjjMQvCl7iQlk2jCvksG28yh622uGuG5m9qEBERuJ+8WG6C6ExQoRiup7UjGgsUgIi6nHaeUQ9Lbbz8Hc2NYToUhmAussThRcn/wByicPFf+KMm0iSP6wErBVkJnRIoybSpAUEwZnK/wDM1z7gXqxgUBCEkQdddp5+Du7a4DUvOxIo0MYypyBCJIzXcvCsDlQashi4FKIEOPOpireXmhSMMuP4LsBXQqISDYe2jQdimQHv0/AqLroFC19Eai4HkyotlA1L+KLkn4DFM5BVzFykmrycfWKxACxuCccL1GwC2WOurUADiF6KRkLSxTKVrgaF0BXIK6/QE0iikxtEetIEswxUNY/geVTVsUNK8QybE5BoW2/IaOwoaxLjoVhQ5gsaSZtRz7EqRhpXcvCgaMCSvCoioWAJMcA1pRCMLC4stEEcN0PdpCXOhKObQlSm6cgNeFDa42pkzc5aX2KyIc6ItILM11wdGicJ5Wjr71N/yQsTjoUSDOEY9EqDF4RMiQ0tm0QMwDqQT3KvRESTGiWfwWmbsC0wFWZ+3ulqfRsKL8GvtQEfPEFifxRRJkKSkTL+KWfNhViXHMM1y6FKSmTCPJocpiWGHPVoIb/FiBryqCCRcJolAUElKauRSIDDAtM8ioDLSwQmk0AUASChk5mw/AaG2/IaOw44Y2udq0sJTzi1CWGKQUibI7AFfK5V5/inBqFzQejHeh0MlexynhQep6ntWZw/tRM870xfhbZmHpZVhcfmvhtCmxWF1FYt5CZRdrSSQYYnhcKYQBWca3KikjOX8FKsuMp1oz5vmsP4WrAqAykkkTE0IEgW0zCMfinc/wAp77wr5HGvD5fhB3HitPGHisnEwuwn3oMTda35njR68XYfgNDbZk0bzsKGkw4a1hUCwvg8HRKWng1scimSuOaPd/Fjv/H4IJwJqcOJUskzKjs19BohgVARxvSpz8sTD7NSELApEqTL6r4V3HzXwmhXbPNHf8lYPmwpQ3HzqwGALhUzKAMAwcgKCAKsbMN+WdONBhmYnS+tDkUt7yuk6FIkSRg6ub+Kdz/Ke88K+Jxp7T5rFqO48UhJgoXRMGltFMS8RycygAkWBkaJQMFQnS8UxgoiYzx1x61ESTMKTrH7zAdW23n4u5sSMsuFcvyBQRQqEhMGkBUxhaI/HyStYcg1wfRpVSStFF3VeabRFikL6UJZ5mC1ymrMc6P+6bwTlv3pT4PNDjBjhP7ReAwuX+0wJZBAAB3ogCAsSGO9LJe4j3r4j3qx5P8AugGYOSA+aXHBgJ8VZyjNY9al7Qs4DetZvOM1n+yMDDSaSSKGhU5F+dCgkJSoSAMCA/A8cwJK0HiANQWZVeZtPBf27UEEfv5+Lu7bzKPpfaYuLOEDrS2g/PFqKlDJl3oAICD96CQklTcZZMu1KTJ098qLiyhK67TyqPrfbfmsDWGzTSOblzNAnAOx96DlWAQGyt2rEJGgeIO79qkkcnLkdn+CwbbEkV8kh2U6QbmH2CiojAG041EAUdAN3H7hssGf9iggjbsP2iepsaYFQAlWgQMXFPe7aCBi4J7WkwKhRCOx4ftN9Db4FLO+Yz/diSAqALrQMw13I6Hvt7MwlnI6PvSQFQhcdikUsZ5rP82+SJY9GD52HHCiK17mT33CDWvYye9YbDBMuegseNvF7BeykMQkJsGJhr3qcjcYPAa16nJ2BDKUgKEbAezcEAEN6mPef3ykgs+sNCMCA03GaaCHSpzUU+kP75CJb0MO8bhhtfoTh38/vwoXL5ZD+7lxIXLZ5j+/vjtfoRj38bhznEODl3ow4RE0f2tEY+ixoABAEBuVBESJCU0Vj6rD9phygBq1kOI8XPvuKQCAj5e/X9sDLnTMe/jc8SLnTcO/n9sQEhPw9+m48dXacT0/YCoF1sUYphjzz77nNcxw55d6RFGyWf2YKu84HpuSHUehOXT9ctkwLkX/AJumOyJByb/39cep9CMutYbkvadfMz9c5mPHNY990xiYfqKe364uJHwzI+a7msKS8FzP1dR+R3T1H4H9UDMh4rkbnWEHQKPcWg5P6YtZ/BumbSfw/pe4sAzaGEPUN0JemB2/S7t4N09u8P6YemD33SDEKEcym5F6C05n6O5eDdPavD+guxOgtObQYhQBkbqtvrfP1KnDGHjx/wDbC7m8FSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalSalMbuTw/+5Qxg4cavnuOfqbshEB3aNGkbIhHEf/Q0CODX3KvuVfcq+5V9yr7lX3KvuVfcq+5V9yr7lX3KvuVfcq+5V9yr7lX3KvuVfcq+5V9yr7lX3KvuVfcq+5V9yr7lX3KvuVfcq+5V9yr7lX3KvuVfcq+5UNCji/8Aom5EAYrUIhO7RobuwhaRy68964QtKmHXnvDPTibHg3nmpxNhxbyzk4gx4ntvHOTiDu+29ISsU7HGcaRuRCJCbtBuRgAlahSxXucbx3s0hMtG3A+9PGyDnxN1vGyBlxaKQuXjbgPffF9dMHsUuTI2VuujumXGBsrdNWrY64vc30WQUISNTdWt8v5Sg2hCE3K4NoAlag6sL5fygyCgCA37FLEyAqwEZdzmbjuBWXd5FRSRGYX+Bu5OXZ5lIsO4h1029kl3AOmtQ8Jy7HI/wsxe+H6mFSwBZ/yp6YYghNpOuGAJWoYBs/5VFWvjxyMCsP8AEcxgS51qbU6UPXGpJU/iMaRIDESHYwSkyCWoJG/xGNRanSh641zGALvX/HRYPgNTKeaj0akE3Rl/anbhqDTcc1SsP040lHNVrPQ1CkAm6Mv5UCnko9CooHwD/KxONdm1a8MkePx8C+A8qfRfaj/hfah4rz/D4PDpPmu3alBGH/zS/wD/2Q==";
    } else {
        avatar = data.UserAvatar;
    }

    var avatarField = document.getElementById("avatar");
    avatarField.style.backgroundImage = `url("data:image/png;base64,${avatar}")`;

    var aboutMeField = document.getElementById("about-me");
    aboutMeField.innerHTML = data.UserProfileRichContent;

    var experienceField = document.getElementById("experiences");
    experienceField.innerHTML = data.UserProfileExperience;
}

url_bearer = "http://localhost:8010/proxy/profile/me";
fetch(url_bearer, {
    method: "GET",
    mode: "cors",
    headers: {
        "Content-Type": "application/json",
        Authorization: `bearer ${localStorage.getItem("accessToken")}`,
    },
})
    .then(function (response) {
        return response.json();
    })
    .then(function (data) {
        console.log(data);
        transferDataToHtml(data);
    })
    .catch(function (error) {
        console.log(error);
    });

document.getElementById("button-save").addEventListener("click", function () {
    new_profile = {
        UserRealName: document.getElementById("user-full-name").value,
        UserEmail: document.getElementById("email").value,
        UserAvatar: document
            .getElementById("avatar")
            .style.backgroundImage.split("base64,")[1]
            .slice(0, -2),
        UserPhoneNumber: document.getElementById("phone").value,
        UserProfileRichContent: document.getElementById("about-me").value,
        UserProfileEducation: document.getElementById("education").value,
        UserProfileExperience: document.getElementById("experiences").value,
    };

    console.log(new_profile);

    fetch("http://localhost:8010/proxy/profile/me", {
        method: "PUT",
        mode: "cors",
        headers: {
            "Content-Type": "application/json",
            Authorization: `bearer ${localStorage.getItem("accessToken")}`,
        },
        accept: "application/json",
        body: JSON.stringify(new_profile),
    })
        .then(function (response) {
            return response.json();
        })
        .then(function (data) {
            console.log(data);
            window.location.href = "/profile/?id=me";
        })
        .catch(function (error) {
            console.log(error);
        });
});
